### ISSUE TITLE
socket: read: camera: invalid JPEG format: uninitialized Huffman table

### ISSUE THREAD

**Issue by 5vr** [gen2brain/cam2ip#51] opened 2024-02-16 10:27 UTC
So, my laptop's integrated camera works no problem, but the USB webcam I'm trying to setup gives this error:
`socket: read: camera: invalid JPEG format: uninitialized Huffman table`
And of course, I can't see any image in the browser. Please help.

**Comment by gen2brain** [comment] 2024-02-16 10:58
This is duplicate of issue #20.

**Closed** 2024-02-16 10:59 UTC
